export const PORTAL_INITIAL_TIME = {
  BOUNTY_HUNTING: 40,
  CASTLE_GATES: 50,
  STORMWING: 35,
  DRAGON_EGG_STEALING: 8,
  COURTSHIP_DANCE: 25,
  EAGLE_HUNTING: 30,
  TOTEM_SLASH: 20,
  INFERNO_WOLF: 25,
};

export const PORTAL_EXP_MULTIPLIER = {
  BOUNTY_HUNTING: 800,
  CASTLE_GATES: 860,
  STORMWING: 1150,
  TOTEM_SLASH: 1200,
  DRAGON_EGG_STEALING: 480,
  COURTSHIP_DANCE: 1200,
  EAGLE_HUNTING: 1200,
  INFERNO_WOLF_EXTREME: 1600,
  INFERNO_WOLF_CHAOS: 1200,
};

export const EVENT_BUFF_STAT = '고브의 축복';
